const JOB_TYPES = {
  ORDER_NOTIFICATION: 'ORDER_NOTIFICATION',
  PAYMENT_RECONCILIATION: 'PAYMENT_RECONCILIATION',
  DELIVERY_NOTIFICATION: 'DELIVERY_NOTIFICATION',
  CACHE_INVALIDATION: 'CACHE_INVALIDATION',
  ANALYTICS_REFRESH: 'ANALYTICS_REFRESH'
};

const JOB_STATES = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
  DEAD_LETTER: 'DEAD_LETTER'
};

module.exports = {
  JOB_TYPES,
  JOB_STATES
};
