const EVENT_TYPES = {
  // Order Events
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_DECISION_UPDATED: 'ORDER_DECISION_UPDATED',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',

  // Payment Events
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Inventory Alerts
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',

  // Promotional Events
  PROMOTION_CREATED: 'PROMOTION_CREATED'
};

module.exports = EVENT_TYPES;
