const EVENT_TYPES = {
  // Order Events
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_DECISION_UPDATED: 'ORDER_DECISION_UPDATED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',

  // Delivery Events
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  DELIVERY_ACCEPTED: 'DELIVERY_ACCEPTED',
  ORDER_PICKED_UP: 'ORDER_PICKED_UP',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  DELIVERY_REASSIGNED: 'DELIVERY_REASSIGNED',

  // Payment & Refund Events
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_INITIATED: 'REFUND_INITIATED',
  REFUND_COMPLETED: 'REFUND_COMPLETED',
  REFUND_FAILED: 'REFUND_FAILED',

  // Inventory Alerts & Lifecycle Events
  LOW_STOCK: 'LOW_STOCK',
  LOW_STOCK_ALERT: 'LOW_STOCK_ALERT',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  STOCK_RESERVED: 'STOCK_RESERVED',
  STOCK_RELEASED: 'STOCK_RELEASED',
  STOCK_CONSUMED: 'STOCK_CONSUMED',

  // Promotional Events
  PROMOTION_CREATED: 'PROMOTION_CREATED',

  // Cancellation, Return & Replacement Events
  ORDER_CANCELLATION_REQUESTED: 'ORDER_CANCELLATION_REQUESTED',
  ORDER_CANCELLATION_UPDATED: 'ORDER_CANCELLATION_UPDATED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_UPDATED: 'RETURN_UPDATED',
  REPLACEMENT_REQUESTED: 'REPLACEMENT_REQUESTED',
  REPLACEMENT_UPDATED: 'REPLACEMENT_UPDATED',
  RETURN_PICKUP_UPDATED: 'RETURN_PICKUP_UPDATED'
};

module.exports = EVENT_TYPES;
