const AppError = require('../utils/AppError');
const { HTTP_STATUS } = require('../constants/statusCodes');

const ORDER_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  CREATED: 'CREATED',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
};

const ALLOWED_TRANSITIONS = {
  [ORDER_STATUS.PENDING_PAYMENT]: [ORDER_STATUS.PAYMENT_PROCESSING, ORDER_STATUS.CONFIRMED, ORDER_STATUS.PAYMENT_FAILED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAYMENT_PROCESSING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.PAYMENT_FAILED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.PAYMENT_FAILED]: [ORDER_STATUS.PENDING_PAYMENT, ORDER_STATUS.PAYMENT_PROCESSING, ORDER_STATUS.CONFIRMED]
};

const validateOrderStatusTransition = (currentStatus, targetStatus) => {
  if (currentStatus === targetStatus) return true;

  const allowed = ALLOWED_TRANSITIONS[currentStatus] || [];
  if (!allowed.includes(targetStatus)) {
    throw new AppError(
      `Invalid order status transition from "${currentStatus}" to "${targetStatus}"`,
      HTTP_STATUS.BAD_REQUEST
    );
  }
  return true;
};

module.exports = {
  ORDER_STATUS,
  PAYMENT_STATUS,
  validateOrderStatusTransition
};
